[package]
name = "libsrt-rs"
version = "0.1.0"
readme = "README.md"
keywords = ["srt", "video", "audio"]
authors = ["Byungwan Jun <unipro.kr@gmail.com>"]
edition = "2018"

[dependencies]
libsrt-sys = { path = "libsrt-sys", version = "0.1.0" }
libc = "0.2"
iovec = "0.1.1"
futures = "0.1.28"
tokio-io = "0.1.12"

failure = { version = "0.1.5", default-features = false, features=["std"] } # XXX only bin dependency

[dev-dependencies]
tokio = "0.1.22"

[workspace]
members = [
    ".",
    "libsrt-sys",
]