[package]
name = "libsrt-rs"
version = "0.1.0"
readme = "README.md"
keywords = ["srt", "video", "audio"]
authors = ["Byungwan Jun <unipro.kr@gmail.com>"]
edition = "2018"

[dependencies]
libsrt-sys = { path = "libsrt-sys", version = "0.1.0" }
libc = "0.2"
iovec = "0.1.1"

failure = "0.1"                 # XXX only bin dependency

[workspace]
members = [
    ".",
    "libsrt-sys",
]